In [ ]:
import numpy as np

1. buat matrix X berukuran 2x3 menggunakan numpy

In [ ]:
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

tampilkan ukuran dari matrix X

In [ ]:
X.shape

(3, 2)

tampilkan seluruh elemen dari kolom pertama dari matrix X

In [ ]:
X[:,0]

array([25,  5,  3])

tampilkan seluruh elemen dari baris kedua dari matrix X

In [ ]:
X[1,:]

array([ 5, 26])

2. ulangi soal nomor 1 menggunakan pytorch

In [ ]:
import torch

In [ ]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [ ]:
X_pt.shape

torch.Size([3, 2])

In [ ]:
X_pt[:,0]

tensor([25,  5,  3])

In [ ]:
X_pt[1,:]

tensor([ 5, 26])

3. ulangi soal nomor 1 menggunakan tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [ ]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [ ]:
X_tf[:,0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25,  5,  3], dtype=int32)>

In [ ]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26], dtype=int32)>