1. Buat vector x dengan ukuran 3x1

In [ ]:
import numpy as np

buat vector x dengan ukuran 3x1

In [ ]:
x = np.array([20, 25, 30])

hitung panjang vector x

In [ ]:
len(x)

3

tampilkan ukuran vector x

In [ ]:
x.shape

(3,)

tampilkan tipe data dari vector x

In [ ]:
type(x)

numpy.ndarray

akses elemen pertama dari vector x

In [ ]:
x[0]

np.int64(20)

tampilkan tipe data elemen pertama dari vector x

In [ ]:
type(x[0])

numpy.int64

2. lakukan transpose pada vector x dan simpan pada variabel x_t

In [ ]:
x_t = x.T
x_t

array([20, 25, 30])

tampilkan ukuran dari vector x_t

In [ ]:
x_t.shape

(3,)

lakukan transpose pada vector y dan simpan pada variabel y_t

In [ ]:
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [ ]:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

tampilkan ukuran dari vector y_t

In [ ]:
y_t.shape

(3, 1)

3. lakukan soal nomor 2 menggunakan pytorch dan tensorflow

In [ ]:
import torch
import tensorflow as tf

TensorFlow

In [ ]:
x_tf = tf.Variable([20, 25, 30])

Pytorch

In [ ]:
x_pt = torch.tensor([25, 2, 5])